### ISSUE TITLE
Chrome Store Github URL is wrong

### ISSUE THREAD

**Issue by jkingsman** [dskang/webtimer#8]
The store description at https://chrome.google.com/webstore/detail/web-timer/ggnjbdfgigejghknieofeahaknkjafim?hl=en is incorrect.

It lists `https://github.com/dskang/webtimer` as the URL for contributions, when it is in fact `https://github.com/dskang/web-timer` (note the hyphen in `web-timer`).

**Comment by dskang** [comment]
Thanks! I changed the name from `webtimer` to `web-timer` a long time ago for reasons I don't remember and forgot to change it back. Fixed now.

**Comment by AnonymousWP** [comment]
Similar issue applies to the "option" page of the extension: chrome-extension://efkkjffdefaaioagghcaflicdajfhceo/options.html. URLs to Chrome Store don't work.
